buildscript {
    repositories {
            mavenCentral()
            maven { url "https://maven.minecraftforge.net" }
            maven { url = "https://repo.spongepowered.org/maven" }
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:${forge_gradle_version}"
    }
}

apply plugin: "net.minecraftforge.gradle.forge"
apply from: "runmanager.gradle"
//Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.

version = project.mod_version
group = "com.hexagram202" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "Subject3"

sourceCompatibility = targetCompatibility = "1.8" // Need this here so eclipse task generates correctly.
compileJava {
    sourceCompatibility = targetCompatibility = "1.8"
}

minecraft {
    version = "1.12.2-14.23.5.2847"
    runDir = "run"
    mappings = "stable_39"
    makeObfSourceJar = true // an Srg named sources jar is made by default. uncomment this to disable.


}

repositories {


    mavenCentral()
}


dependencies {

}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property "mod_version", project.version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include "mcmod.info"

        // replace version and mcversion
        expand "mod_version":project.mod_version
    }

    // copy everything else except the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude "mcmod.info"
    }
}