modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="subject3"
version="${file.jarVersion}"
displayName="Subject Three: Sweet Dreams"
logoFile="logo.png"
credits="Liu Dongyu"
authors="Hexagram"
description='''
A meme mod related to a candidate for driving test subject three who performs funnily.

With this mod, you can make bed boat and bed minecart to set a moving respawn point.
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
