modLoader="javafml"
loaderVersion="[46,)"
license="GNU Affero General Public License v3.0"
issueTrackerURL="https://github.com/Viola-Siemens/Subject-Three-Sweet-Dreams/issues"

[[mods]]
modId="subject3"
version="${file.jarVersion}"
displayName="Subject Three: Sweet Dreams"
logoFile="logo.png"
credits="Liu Dongyu"
authors="Hexagram"
description='''
A meme mod related to a candidate for driving test subject three who performs funnily.

With this mod, you can make bed boat and bed minecart to set a moving respawn point.
'''

[[dependencies.subject3]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.subject3]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
