name: Build Test Artifact

on:
  push:

jobs:
  build:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest

    steps:
          - name: Checkout Repository
            uses: actions/checkout@v4.1.4
          - name: Gather Gradle properties
            uses: madhead/read-java-properties@latest
            id: gradle_properties
            with:
                 file: gradle.properties
                 all: true

          - name: Grant Execute Permission for gradlew
            run: chmod +x gradlew
          - name: Cache Gradle
            uses: actions/cache@v3
            with:
              path: 
                ~/gradle/
                ~/.gradle/
                ~/build/
              key: ${{hashFiles('build.gradle') }}-${{hashFiles('gradle.properties') }}
              restore-keys: |
                ${{hashFiles('build.gradle') }}-${{hashFiles('gradle.properties') }}
          - name: Change mod version
            run: sed -i "s/mod_version.*=.*/mod_version = ${{github.ref_name}}.${{ github.run_number}}/g" gradle.properties
          - name: Setup Java
            uses: actions/setup-java@v4.2.1
            with:
              java-version: '17'
              distribution: 'zulu'
              cache: gradle
          - name: Build
            run: ./gradlew build
          - name: Upload Build Artifacts
            uses: actions/upload-artifact@v4.3.3
            with:
              name: subject3-snapshot-${{ github.run_number}}.jar
              path: build/libs